name: 'test'

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Move .env.example to .env
        run: |
          cp .env.example .env

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Check that the code is valid Typescript
        run: yarn tsc --parallel

      - name: Check that the code passes linting
        run: yarn lint --parallel

      - name: Run package tests
        run: yarn test --parallel
